### ISSUE TITLE
I replace with golds historical data but not work

### ISSUE THREAD

**Issue by inputsets** [thorie7912/bitcoin-calculator#8]
Dear thorie,
i'm used tools but i replace other price here is gold price, s&p 500 stock index but not work.
The problem is that the stock and gold trading data are empty on weekends.

Need you update the code and fixis

Thanks so much.
![image](https://user-images.githubusercontent.com/91039496/133951045-600362d5-baa9-477b-b6db-4c2010524f30.png)

**Comment by microlancer** [comment]
I've fixed the issue in PR #9 you can see the changes here:

https://github.com/thorie7912/bitcoin-calculator/pull/9/files

**Comment by inputsets** [comment]
i tried it works, however with data more than 20 days it gives error. Can you add an unlimited number of days solution?
Because in the past, the price of gold traded since 1979 has not been weekly.

![image](https://user-images.githubusercontent.com/91039496/133974500-45f6b517-08e4-4556-a477-d889522621b2.png)

**This is my gold price:**
https://dropfiles.org/T70nk7hX
